mpirun -np 10 ../build/fsi_tet4_3d -nz_estimate 300 \
  -nqp_tet 5 -nqp_tri 13 \
  -init_step 1.0e-6 -fina_time 2.0e-3 \
  -nl_refreq 2 -nl_rtol 1.0e-6 -nl_atol 1.0e-15 -nl_dtol 1.0e2 \
  -nl_maxits 8 \
  -log_view -ttan_freq 100 -sol_rec_freq 500 \
  -is_restart NO -restart_index 79500 -restart_time 7.95e-3 \
  -restart_step 1.0e-7 \
  -restart_u_name SOL_U_re \
  -restart_v_name SOL_V_re \
  -restart_p_name SOL_P_re \
  -mesh_ksp_type gmres -mesh_pc_type hypre \
  -mesh_ksp_rtol 5.0e-3 -mesh_ksp_max_it 100 \
  -mesh_pc_hypre_boomeramg_coarsen_type HMIS \
  -mesh_pc_hypre_boomeramg_interp_type ext+i \
  -mesh_pc_hypre_boomeramg_truncfactor 0.3 \
  -mesh_pc_hypre_boomeramg_strong_threshold 0.7 \
  -mesh_pc_hypre_boomeramg_P_max 5 \
  -mesh_pc_hypre_boomeramg_agg_nl 2 \
  -ksp_type fgmres -pc_type fieldsplit -pc_factor_mat_solver_type mumps \
  -pc_fieldsplit_type schur \
  -pc_fieldsplit_schur_factorization_type full \
  -pc_fieldsplit_schur_precondition selfp \
  -fieldsplit_p_mat_schur_complement_ainv_type diag \
  -ksp_rtol 1.0e-2 \
  -ksp_atol 1.0e-50 \
  -ksp_max_it 1000 \
  -ksp_gmres_restart 1000 \
  -fieldsplit_u_ksp_type gmres \
  -fieldsplit_u_pc_type jacobi \
  -fieldsplit_u_ksp_rtol 1.0e-2 \
  -fieldsplit_u_ksp_max_it 100 \
  -fieldsplit_u_ksp_gmres_restart 100 \
  -fieldsplit_p_ksp_type gmres \
  -fieldsplit_p_pc_type hypre \
  -fieldsplit_p_pc_hypre_boomeramg_coarsen_type HMIS \
  -fieldsplit_p_pc_hypre_boomeramg_interp_type ext+i \
  -fieldsplit_p_pc_hypre_boomeramg_truncfactor 0.3 \
  -fieldsplit_p_pc_hypre_boomeramg_strong_threshold 0.5 \
  -fieldsplit_p_pc_hypre_boomeramg_P_max 5 \
  -fieldsplit_p_pc_hypre_boomeramg_agg_nl 2 \
  -fieldsplit_p_ksp_rtol 5.0e-2 \
  -fieldsplit_p_ksp_max_it 100 \
  -fieldsplit_p_ksp_gmres_restart 100 \
  -log_view \
  -fieldsplit_p_inner_ksp_type preonly \
  -fieldsplit_p_inner_pc_type jacobi \
  -fieldsplit_p_upper_ksp_type preonly \
  -fieldsplit_p_upper_pc_type jacobi

